version: '3.8'
services:
  postgres:
    image      : postgres:16-alpine
    restart    : always
    environment:
      - POSTGRES_USER=lastdisco_admin_db
      - POSTGRES_PASSWORD=Eequo2quAiBok9su
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local